apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: alien-nginx
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: alien-nginx
  minReplicas: 1
  maxReplicas: 6
  targetCPUUtilizationPercentage: 30